CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE driver ALTER COLUMN id DROP IDENTITY;

ALTER TABLE driver ALTER COLUMN id TYPE UUID USING gen_random_uuid();

ALTER TABLE driver ALTER COLUMN id SET DEFAULT gen_random_uuid();
