CREATE TABLE IF NOT EXISTS public.car
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    license_plate character varying(255) COLLATE pg_catalog."default" NOT NULL,
    mark character varying(255) COLLATE pg_catalog."default" NOT NULL,
    colour character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean,
    CONSTRAINT car_pkey PRIMARY KEY (id),
    CONSTRAINT car_license_plate_key UNIQUE (license_plate)
)
GO

ALTER TABLE public.driver
ADD CONSTRAINT driver_car_id_fkey FOREIGN KEY (car_id)
    REFERENCES public.car (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
GO