global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'eureka:8761'
          - 'gateway:8765'
          - 'driver-service:8081'
          - 'passenger-service:8082'
          - 'rides-service:8083'
          - 'rating-service:8084'
