spring.application.name=storage-service

server.port=8086

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWK_JWKSETURI}

minio.url=${MINIO_URL}
minio.access.name=${MINIO_ACCESS_NAME}
minio.access.secret=${MINIO_ACCESS_SECRET}
minio.bucket.name=${MINIO_BUCKET_NAME}

spring.cloud.config.import-check.enabled=false