spring.application.name=storage-service

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

minio.url=${MINIO_URL}
minio.access.name=${MINIO_ACCESS_NAME}
minio.access.secret=${MINIO_ACCESS_SECRET}
minio.bucket.name=${MINIO_BUCKET_NAME}