create TABLE IF NOT EXISTS public.ride
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    driver_id bigint NOT NULL,
    passenger_id bigint NOT NULL,
    from_address text NOT NULL,
    to_address text NOT NULL,
    ride_status character varying(50) NOT NULL,
    order_date_time timestamp NOT NULL,
    cost numeric(10, 2) NOT NULL,
    CONSTRAINT driver_pkey PRIMARY KEY (id),
)
GO