name: Maven Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build exception-handler module
        run: mvn --batch-mode clean install -pl exception-handler -am

      - name: Run Unit Tests
        run: mvn --batch-mode test
